name: .mpy file format and tools

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04 # use 20.04 to get python2
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_mpy_format_setup
    - name: Test mpy-tool.py
      run: source tools/ci.sh && ci_mpy_format_test
