name: Build ports metadata

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build ports download metadata
      run: mkdir boards && ./tools/autobuild/build-downloads.py . ./boards
