name: renesas-ra port

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_renesas_ra_board:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_renesas_ra_setup
    - name: Build
      run: source tools/ci.sh && ci_renesas_ra_board_build

