name: esp8266 port

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci.sh && ci_esp8266_setup && ci_esp8266_path >> $GITHUB_PATH
    - name: Build
      run: source tools/ci.sh && ci_esp8266_build
    - name: "Upload binary"
      uses: actions/upload-artifact@v4
      with:
          name: "ESP8266_GENERIC-FLASH_1M.bin"
          path: |
            /home/runner/work/micropython/micropython/ports/esp8266/build-ESP8266_GENERIC-FLASH_1M/firmware.bin
